// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DISCORD_CLIENT`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `initialize`

Future<void> initDiscordRpc({required String clientId}) =>
    RustLib.instance.api.crateApiDiscordInitDiscordRpc(clientId: clientId);

Future<void> setDiscordPresence(
        {required String state,
        required String details,
        required PlatformInt64 startTimestamp}) =>
    RustLib.instance.api.crateApiDiscordSetDiscordPresence(
        state: state, details: details, startTimestamp: startTimestamp);

Future<void> clearDiscordPresence() =>
    RustLib.instance.api.crateApiDiscordClearDiscordPresence();
