name: Build Windows App

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter (Native PowerShell)
        run: |
          if (-not (Test-Path "C:\flutter")) {
            git clone https://github.com/flutter/flutter.git -b stable C:\flutter
          }
          echo "C:\flutter\bin" >> $env:GITHUB_PATH

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows App
        run: flutter build windows

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: liquid-launcher-windows
          path: build/windows/x64/runner/Release/
